// Project portfolio — structure only. `title` and `techStack` are proper nouns and
// stay untranslated. Translatable copy lives in locales:
// projectsSection.items.<_id>.{description,longDescription}
export const PROJECTS = [
  {
    _id: 'leagues-gg',
    title: 'Leagues.gg — Esports Stats & Social Platform',
    techStack: ['React', 'MUI', 'Node.js', 'Express', 'MongoDB'],
    category: 'fullstack',
    featured: true,
    order: 3,
    status: 'completed',
    liveUrl: 'https://leagues.gg/',
    githubUrl: null,
    imageUrl: 'https://s0.wp.com/mshots/v1/https://leagues.gg/?w=800&h=450',
  },
  {
    _id: 'procurement-league',
    title: 'Procurement League — B2B Learning Community',
    techStack: ['React', 'MUI', 'Tailwind CSS', 'Node.js', 'Express', 'MongoDB'],
    category: 'fullstack',
    featured: false,
    order: 4,
    status: 'completed',
    liveUrl: 'https://procurementleague.com/',
    githubUrl: null,
    imageUrl: 'https://s0.wp.com/mshots/v1/https://procurementleague.com/?w=800&h=450',
  },
  {
    _id: 'influencify',
    title: 'Influencify — Influencer Marketing Platform',
    techStack: ['React', 'MUI', 'Node.js', 'Express', 'MongoDB'],
    category: 'fullstack',
    featured: true,
    order: 5,
    status: 'completed',
    liveUrl: 'https://influencify.co/',
    githubUrl: null,
    imageUrl: 'https://s0.wp.com/mshots/v1/https://influencify.co/?w=800&h=450',
  },
  {
    _id: 'tugamemaster',
    title: 'TuGameMaster — Game Session Booking Platform',
    techStack: ['React', 'Ant Design', 'Redux', 'NestJS', 'PostgreSQL', 'Stripe'],
    category: 'fullstack',
    featured: true,
    order: 6,
    status: 'completed',
    liveUrl: null,
    githubUrl: null,
    imageUrl:
      'https://fiverr-res.cloudinary.com/image/upload/f_auto,q_auto,t_portfolio_project_grid_non_exp/v1/attachments/project_item/attachment/8819cb6cc63d7329a877a31e8ed6547e-1714287264049/Screenshot%202024-04-28%20114614.png',
  },
  {
    _id: 'yoogo',
    title: 'Yoogo — Social Marketplace Platform',
    techStack: ['Next.js', 'MUI', 'Tailwind CSS', 'Redux', 'WebSockets', 'Braintree'],
    category: 'frontend',
    featured: true,
    order: 1,
    status: 'completed',
    liveUrl: 'https://www.yoogo.com/',
    githubUrl: null,
    imageUrl: 'https://s0.wp.com/mshots/v1/https://www.yoogo.com/?w=800&h=450',
  },
  {
    _id: 'canonizer',
    title: 'Canonizer — Consensus & Opinion Mapping',
    techStack: ['Next.js', 'Ant Design', 'Tailwind CSS', 'Redux', 'D3.js', 'NestJS', 'SQL'],
    category: 'fullstack',
    featured: true,
    order: 2,
    status: 'completed',
    liveUrl: 'https://canonizer.com/',
    githubUrl: null,
    imageUrl: 'https://s0.wp.com/mshots/v1/https://canonizer.com/?w=800&h=450',
  },
  {
    _id: 'voltora-solar',
    title: 'Voltora Solar — Solar Energy Platform',
    techStack: ['React', 'MUI', 'Tailwind CSS', 'Redux'],
    category: 'frontend',
    featured: false,
    order: 7,
    status: 'completed',
    liveUrl: 'https://voltora-solar-800168759398.asia-southeast1.run.app/',
    githubUrl: null,
    imageUrl: '/projects/solar-panel.webp',
  },
  {
    _id: 'nexus-grid',
    title: 'Nexus Grid — Solar Management System',
    techStack: ['React', 'MUI', 'Tailwind CSS', 'Redux'],
    category: 'frontend',
    featured: true,
    order: 8,
    status: 'completed',
    liveUrl: 'https://nexus-grid-energy-c8drw2odr.vercel.app/',
    githubUrl: null,
    imageUrl: '/projects/solar-2.webp',
  },
  {
    _id: 'lumiere-aesthetics',
    title: 'Lumière Aesthetics — Beauty Clinic Website',
    techStack: ['React', 'MUI', 'Tailwind CSS', 'Redux'],
    category: 'frontend',
    featured: false,
    order: 9,
    status: 'completed',
    liveUrl: 'https://lumi-re-aesthetics-800168759398.asia-southeast1.run.app/',
    githubUrl: null,
    imageUrl: '/projects/lumi.webp',
  },
  {
    _id: 'oralence-smile',
    title: 'Oralence Smile Studio — Dental Clinic Website',
    techStack: ['React', 'MUI', 'Tailwind CSS', 'Redux'],
    category: 'frontend',
    featured: false,
    order: 10,
    status: 'completed',
    liveUrl: 'https://oralence-smile-studio-9r8ez4wf2.vercel.app/',
    githubUrl: null,
    imageUrl: '/projects/oralence-smile.webp',
  },
  {
    _id: 'valancia-leisure',
    title: 'Valancia Leisure Club — Community & Lifestyle',
    techStack: ['React', 'MUI', 'Tailwind CSS', 'Redux'],
    category: 'frontend',
    featured: false,
    order: 11,
    status: 'completed',
    liveUrl: 'https://valancia-leisure-club-m3wcwpk47.vercel.app/',
    githubUrl: null,
    imageUrl: '/projects/valancia-leisure-club.webp',
  },
  {
    _id: 'finance-tracker',
    title: 'Finance Tracker — Personal Finance Dashboard',
    techStack: ['React', 'MUI', 'Tailwind CSS', 'Redux', 'Node.js', 'Express', 'MongoDB'],
    category: 'fullstack',
    featured: true,
    order: 12,
    status: 'completed',
    liveUrl: 'https://personal-finance-tracker-1dynbw3we.vercel.app/',
    githubUrl: null,
    imageUrl: '/projects/personal-finance.webp',
  },
  {
    _id: 'solarops-pro',
    title: 'SolarOps Pro — Solar ERP Management System',
    techStack: ['React', 'MUI', 'Tailwind CSS', 'Redux', 'Node.js', 'Express', 'MongoDB'],
    category: 'fullstack',
    featured: true,
    order: 13,
    status: 'completed',
    liveUrl: 'https://solarops-dl8fco5ia-ayeshaashrafsoftmindsolutions-5658s-projects.vercel.app/',
    githubUrl: null,
    imageUrl: '/projects/solar-erp.webp',
  },
];
